### PR TITLE
Ensure proper routing of message.response

### LINKED ISSUE #29: message.response should use message.reply internally
to account for proper message routing https://github.com/JarbasHiveMind/HiveMind-core/wiki/Mycroft-Messages + https://github.com/MycroftAI/mycroft-core/pull/2461

### PR DESCRIPTION
**Pull request by JarbasAl**
This ensures the correct routing information is provided in the response. It also maintains all data and context of the message being responded to.

Fixes #29

### CODE REVIEW

**Comment by forslund** [comment]
Can you bump the version to 0.10.0 as well. It will likely be an issue in the Mycroft-core common play / query skills but I need to verify that.

**Comment by krisgesling** [comment]
Hey, on the surface it looks like the behaviour that should be expected. The docstring even says it is a reply.

It would be really useful to have more detailed commit messages and PR descriptions. Even if it's copied verbatim from another source, it means people looking at this PR or the commit history don't need to trawl through other docs to find the relevant pieces and make guesses about why this change is needed.

I'm also wondering if we can add in some more tests here. There seems to be a minimal test for response and nothing for reply, and this potentially breaking change didn't register as an issue on the existing test.

**Comment by JarbasAl** [comment]
related change https://github.com/OpenVoiceOS/skill-ovos-common-query/commit/2189e60b204b9f8b96d7a64429627736b714f399

**Comment by NeonDaniel** [comment]
Anything holding up this PR? Appears related to a routing question I had

**Comment by krisgesling** [comment]
Hey, thanks for adding those unit tests.

I've updated the title and description a little - can you just confirm this is accurate and then we can merge it in.

**Review by krisgesling — APPROVED** [review]

**Pull request merged**
