### PR TITLE
Wait for message

### PR DESCRIPTION
**Pull request by forslund**
#### Description
Adds the missing `wait_for_message()` method along with the refactor of wait_for_response to use a shared MessageWaiter class.

This also incorporates the very excellent update from @NeonDaniel to utilize the Event instead of a sleep loop. See his description in #18.

#### Type of PR
- [ ] Bugfix
- [x] Feature implementation
- [x] Refactor of code (without functional changes)
- [ ] Documentation improvements
- [ ] Test improvements

#### Testing
Check unittests and assert that this keeps the speed added by @NeonDaniel.

### CODE REVIEW

**Comment by forslund** [comment]
@NeonDaniel do you think you could try to review this PR?

**Comment by NeonDaniel** [comment]
> @NeonDaniel do you think you could try to review this PR?

Sure, I'll start that in a few minutes

**Review by NeonDaniel — APPROVED** [review]
Needs a version bump, but changes look good, confirmed response waiting still sees the same benefit

**Comment by NeonDaniel** [comment]
Side note: I tried dropping in the MessageBusClient (and Message) from this package in skills and got the following error logged (presumably when converse is called). I don't tthink this is related to this PR though (tried with the latest stable and got the same error; probably something I'm missing in the implementation like a mixed import from the core module elsewhere.. I'm going to try replacing the Message and MessageBusClient in core with these imports next.

13:35:29.075 - concurrent.futures - ERROR - exception calling callback for <Future at 0x7f0b537cbf98 state=finished raised TypeError>

**Comment by forslund** [comment]
Ok will bump the version and Merge

**Pull request merged**
